# Generated by Django 5.1.7 on 2025-03-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('duracion', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Etiquetas',
        ),
        migrations.DeleteModel(
            name='Protocolo',
        ),
    ]
