# Generated by Django 5.1.7 on 2025-03-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_curso_delete_etiquetas_delete_protocolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='duracion',
            field=models.IntegerField(max_length=40),
        ),
    ]
