# Generated by Django 5.1.7 on 2025-03-28 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_instructor'),
        ('servicios', '0003_alter_curso_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='duracion',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacion.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.curso')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacion.instructor')),
            ],
        ),
    ]
